name: CI Pipeline

on:
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: portfolio-test-image
  REGISTRY: ghcr.io

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    environment: testing # The Github environment to use
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: create env.testing file
        run: echo "${{ secrets.ENV_FILE_TESTING }}" > .env.testing

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:testing
          load: true
          target: test # Target the test build target in the Dockerfile


      - name: Run Tests
        run: |
          docker run --env-file .env.testing ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:testing php artisan test
